### ISSUE TITLE
Separate host settings

### ISSUE THREAD

**Issue by touwwouter** [DataStewardshipWizard/dsw-client#24]
In order to approach the wizard remotely, I had to change `package.json`:

```
 "start": "webpack-dev-server --host 0.0.0.0 --public <host>:<port>"
```

and  `src/elm/Requests.elm`:

```
apiRoot = "http://<host>:<port>"
```

It would be nice if these could be made settings, in a config file for example.

**Comment by janslifka** [comment]
I moved this to dsw-common (DataStewardshipWizard/dsw-common#96) where we want to keep track of all issues.
