### ISSUE TITLE
*.answer::before and p.advice::before content not rendered properly

### ISSUE THREAD

**Issue by mkuzak** [DataStewardshipWizard/dsw-client#28]
In exported questionnaire html file, the content in `*.answer::before` and `p.advice::before` renders as seen in screenshot below.

<img width="1273" alt="screen shot 2018-07-02 at 15 43 25" src="https://user-images.githubusercontent.com/208443/42167782-593e3d9a-7e0f-11e8-9fb6-81bcea892983.png">

**Comment by janslifka** [comment]
This is not related to client since the documents are generated on backend. I moved the issue to dsw-common (DataStewardshipWizard/dsw-common#95) where we want to keep track of all issues anyway.
